[general]
device = cuda:2
filename = pems08
save = ./save/pems08/
seq_len = 12
num_nodes = 170
train_ratio = 0.6
valid_ratio = 0.2

[train]
epochs = 100
batch_size = 16
lr = 0.001
weight_decay = 0
lr_decay = True
lr_decay_steps = 40,70,90
lr_decay_rate = 0.5
dropout = 0.1
step_size = 100

[model]
sigma1 = 0.1
sigma2 = 10
thres1 = 0.6
thres2 = 0.5

node_dim = 40
subgraph_size = 20
num_split = 1
tanhalpha = 3

in_dim = 1
conv_channels = 64
end_channels = 128
num_hidden_layers = 4

solver_1 = euler
time_1 = 1.0
step_1 = 0.25
solver_2 = euler
time_2 = 1.0
step_2 = 0.5
alpha = 1.0
rtol = 1e-4
atol = 1e-3
